### ISSUE TITLE
Performance Counter ThresholdInterval Problems

### ISSUE THREAD

**Issue by GreyKestrel** [Icinga/icinga-powershell-framework#336] opened 2021-08-18 09:09 UTC
## Expected Behavior
After registering a PerformanceCounter, a query is to be executed in which the average value of two minutes is to be determined and outputted.

## Current Behavior
After running the check in the Powershell console we only get an Unknown with a supposed error where the previously defined Average value is not defined.
See screenshot. 

![image](https://user-images.githubusercontent.com/89130490/129870885-99fdb1d0-bcb6-47a4-a10d-d1ecaf9643f1.png)

Registration command: 
`Register-IcingaServiceCheck -CheckCommand Invoke-IcingaCheckPerfCounter -Arguments @{ '-PerfCounter' = '\FileMaker Server 18\Cache Hit %'; } -TimeIndexes 1, 2, 3, 5 -Interval 30;`

![image](https://user-images.githubusercontent.com/89130490/129871018-8fcb337f-bab8-4935-9155-286813addb36.png)

Without the parameter ThresholdInterval we get an actual result

## Your Environment

* PowerShell Version 4
Tested with Icinga Powershell Framework 1.50, 1.51, 1.52 und 1.60
* Operating System Windows Server 2012 R2

**Comment by LordHepipud** [comment] 2021-08-18 20:25
Hello, thank you for the issue. Could you please share the following information?

```powershell
Get-Service icingapowershell;
Get-IcingaBackgroundDaemons;
Test-IcingaAgent;
(Get-IcingaServices 'icingapowershell', 'icinga2').Values.configuration;
Get-Content -Path (Join-Path -Path (Get-IcingaFrameworkRootPath) -ChildPath '\cache\sc_daemon\checkresult\Invoke-IcingaCheckPerfCounter.json') -Raw;
Get-Content -Path (Join-Path -Path (Get-IcingaFrameworkRootPath) -ChildPath '\cache\sc_daemon\checkresult_store\Invoke-IcingaCheckPerfCounter.json') -Raw;
```

**Comment by GreyKestrel** [comment] 2021-08-19 06:10
Hello, here the informations you asked about.

![image](https://user-images.githubusercontent.com/89130490/130016215-fffb73de-1a7a-4c8f-b6a2-9a96a5a3e0f2.png)

![image](https://user-images.githubusercontent.com/89130490/130016685-d438750d-6c90-4d25-adf6-1536664bea9d.png)

![image](https://user-images.githubusercontent.com/89130490/130016811-65d6b316-0750-4a63-b5aa-877686076d32.png)

thank you for your help.

**Comment by LordHepipud** [comment] 2021-08-19 07:39
Do you have multiple checks configured for `Invoke-IcingaCheckPerfCounter` on the service check daemon? Because there are CPU and FileMaker Datapoints inside.

Could you please share `Show-IcingaRegisteredServiceChecks` again?

If you configured two entries for the check, the problem will be resolved by combining them to one with both argument entries in one task.

**Comment by GreyKestrel** [comment] 2021-08-19 09:00
Yes we did. 
![image](https://user-images.githubusercontent.com/89130490/130040297-5192825b-775a-4f1e-a0e2-fd5cb45cb15d.png)

But we tried it with only one, with the same result.

**Comment by LordHepipud** [comment] 2021-09-07 12:46
I'm not fully sure on why this error occurs. I tested on multiple different systems and couldn't find a problem regarding the writing.
Would it be possible to test this again with todays released v1.6.0?

We fixed the file reader/writer, to properly handle cross-access for files. Maybe this resolves the issue. Otherwise we would require more troubleshooting steps to track down the problem.

**Comment by GreyKestrel** [comment] 2021-09-21 06:36
We now tested it with the Plugins Version 1.6.0 and the Framework Version 1.6.1 . We did manage to combine the checks in one service check i think... 
![image](https://user-images.githubusercontent.com/89130490/134120402-4d7bb643-5e8b-4426-a114-ea50c1d1932b.png)

But now there are no files in the checkresult or the checkresult_store folders and when I run the check there is no ThresholdInterval in the result:
![image](https://user-images.githubusercontent.com/89130490/134121042-189a1c62-dc38-4be4-b0b3-4511e1af0621.png)

**Comment by LordHepipud** [comment] 2021-09-21 14:57
This is a really weird issue which seems to look fine from configuration.

Could you please verify that all your steps are done similar to the ones described inside the new documentation for this: [Collect metrics over time](https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/06-Collect-Metrics-over-Time/)

Based on my test environments, I'm unable to reproduce this issue.

**Comment by GreyKestrel** [comment] 2021-09-23 06:36
I got it to work. The error was that the Icinga Powershell service wouldn't start every time you restarted it after registering a service check or setting up the daemon. 

Workaround is to do everything until the service doesn't start anymore and then delete all folders from the framework folder except the config folder. Then reinsert everything again and start the service.
Shortly after, everything is created in the cache folder as desired and works

**Closed** 2021-11-04 14:16 UTC
Labels: Feedback
