### ISSUE TITLE
Perflib / Perfnet errors in the eventlog while executing Invoke-IcingaCheckCPU

### ISSUE THREAD

**Issue by bieba** [Icinga/icinga-powershell-framework#253] opened 2021-05-21 12:42 UTC
I am getting several errors while executing the Invoke-IcingaCheckCPU command.

## Expected Behavior
No errors in the eventlog.

## Current Behavior
I am getting several errors, e.g.
```
Protokollname: Application
Quelle:        Microsoft-Windows-Perflib
Datum:         21.05.2021 14:33:04
Ereignis-ID:   1008
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      XXX
Beschreibung:
Die Open-Prozedur für den Dienst "WmiApRpl" in der DLL "C:\Windows\system32\wbem\wmiaprpl.dll" war nicht erfolgreich. Die Leistungsdaten für diesen Dienst sind nicht verfügbar. Die ersten vier Bytes (DWORD) des Datenbereichs enthalten den Fehlercode.
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Perflib" Guid="{13B197BD-7CEE-4B4E-8DD0-59314CE374CE}" EventSourceName="Perflib" />
    <EventID Qualifiers="49152">1008</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-21T12:33:04.000000000Z" />
    <EventRecordID>2374253</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>XXX</Computer>
    <Security />
  </System>
  <UserData>
    <EventXML xmlns="Perflib">
      <param1>WmiApRpl</param1>
      <param2>C:\Windows\system32\wbem\wmiaprpl.dll</param2>
      <binaryDataSize>8</binaryDataSize>
      <binaryData>1500000000000000</binaryData>
    </EventXML>
  </UserData>
</Event>
```

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Simply invoke ```Invoke-IcingaCheckCPU```

## Context
Errors occur while normal operation.

## Your Environment

* PowerShell Version used (`$PSVersionTable.PSVersion`):
```
PS C:\Temp> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018
```

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
```
PS C:\Temp> Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption

Version  BuildNumber Caption
-------  ----------- -------
6.3.9600 9600        Microsoft Windows Server 2012 R2 Datacenter
```

Before I recognized, that the issues are caused by Icinga I tried to repair the performance counters like advised [here](https://audministrator.wordpress.com/2018/08/20/windows-server-2016-perflib-error-event-id-1008/).

**Comment by LordHepipud** [comment] 2021-05-22 09:23
There is already a similar issue open on the plugins: https://github.com/Icinga/icinga-powershell-plugins/issues/119

This problem is something we can't resolve. We even had some discussions with a Microsoft Consultant, and even he could not resolve it.

The issue is not that your Performance Counters are broken, you just don't have the permission to access this specific counter with the user running this command.

The current implementation will create a Performance Counter object for `Processor` for example. But by doing so, it will load the entire perflib in the background. In case the system cannot access a certain perflib, because you are not having permissions to access it, you see this error.

The only way to get rid of this right now, would be to use the REST-Api background experimental: [Icinga Docs](https://icinga.com/docs/icinga-for-windows/latest/doc/experimental/01-Forward-checks-to-internal-API/)

In the future we might get this resolved by fulling switching to JEA-Profiles for plugin execution.

**Comment by log1-c** [comment] 2021-05-28 07:47
The event stop when the Icinga Agent and PS Framework service are configured as a System service.
At least we could resolve it that way, as we previously had the services running as Network Service

**Comment by LordHepipud** [comment] 2021-06-02 10:31
I have added a IKBW entry with linked PR for this.

**Closed by LordHepipud** 2021-06-02 10:31 UTC
Labels: Documentation
